meta.pc = 20H0417
meta.old.pc = 19H0116
privat.pc = PRIVAT-PC
schmi.pc = DESKTOP-Q6O0UGB
test.pc = DESKTOP-LERLCJ6
tim.pc = Tim-PC

logpath.meta = C:\\Users\\TSZ\\Daten\\Java\\Applications\\xdoc\\logs
logpath.meta.old = C:\\Users\\TSZ\\Daten\\Java\\Applications\\xdoc\\logs
logpath.privat = C:\\Users\\Administrator\\Daten\\Java\\Applications\\xdoc\\logs
logpath.schmi = C:\\Users\\schmi\\Daten\\Java\\Applications\\xdoc\\logs
logpath.test = C:\\Users\\Test\\Daten\\Java\\Applications\\xdoc\\logs
logpath.tim = C:\\Users\\Tim\\Daten\\Java\\zApplications\\xdoc\\logs

basepath.meta = C:\\Users\\TSZ\\Daten\\Web\\xdoc
basepath.meta.old = C:\\Users\\TSZ\\Daten\\Web\\xdoc
basepath.privat = C:\\Users\\Administrator\\Daten\\Web\\xdoc
basepath.schmi = C:\\Users\\schmi\\Daten\\Web\\xdoc
basepath.test = C:\\Users\\Test\\Daten\\Web\\xdoc
basepath.tim = C:\\Users\\Tim\\Daten\\Web\\xdoc

user.name = Tim Schmitz
error.host = Kein Computername definiert
localhost.xdoc = http://localhost:8080/xdoc
