#-----------------------#
# Allgemeine Parameter  #
#-----------------------#
projects            = C:/Users/TSZ/Daten/Java/Projects
runtime             = C:/Users/TSZ/Daten/Java/Applications
libraries           = C:/Users/TSZ/Daten/Java/Libraries

#-----------------------#
# Projekt-Parameter     #
#-----------------------#
project.xdoc        = ${projects}/xdoc
project.source      = ${project.xdoc}/src
project.properties  = ${project.xdoc}/properties
project.metainf     = ${project.xdoc}/META-INF

#-----------------------#
# Laufzeit-Parameter    #
#-----------------------#
runtime.xdoc        = ${runtime}/xdoc
runtime.build       = ${runtime.xdoc}/build
runtime.properties  = ${runtime.xdoc}/properties
runtime.metainf     = ${runtime.xdoc}/META-INF

#-----------------------#
# Bibliotheken          #
#-----------------------#
log4j.api           = ${libraries}/apache-log4j-2.11.1-bin
junit.api           = ${libraries}/junit-5
batik.api           = ${libraries}/batik-1.12/lib
fop.api             = ${libraries}/fop-2.3/fop/lib
fop.build           = ${libraries}/fop-2.3/fop/build

#-----------------------#
# Test-Parameter        #
#-----------------------#
project.test        = ${project.xdoc}/test
runtime.test        = ${runtime.xdoc}/test
runtime.output      = ${runtime.xdoc}/output
